### ISSUE TITLE
where the webhook url i get from?

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [HekaHealth/heka-health-plugin#1]
in create app in hekaHealth dashboard, i have to set "webhook url". what is webhook and how i get it?

**Comment by Pulkit07** [comment]
This is a webhook that you need to expose on which data gathered from various fitness data sources will be sent. For details on the data format, you can check out our [relevant documentation](https://heka-health.notion.site/Getting-data-on-the-server-Heka-94ae2c8228ad426c9a45f3ac1d7312fe).

We are closing the issue for now; feel free to ask any questions.
