### ISSUE TITLE
My data sent by webhook url is always null

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [HekaHealth/heka-health-plugin#3]
Hi, I have succed in connect to heka wealth plugin, but my data I get in my server side is a literally same the data format in your documentation but is null in (value, source, endtime,starttime). Why this happen, have I forget any thing.
By the way, permissions not request to grant in the app, I have to go to the settings of device to grant (activity recognition, body sensor) I found not granted and switch it on manually.

**Comment by Pulkit07** [comment]
> Hi, I have succed in connect to heka wealth plugin, but my data I get in my server side is a literally same the data format in your documentation but is null in (value, source, endtime,starttime). Why this happen, have I forget any thing.

Let me check our server logs and get back to you on this.


> By the way, permissions not request to grant in the app, I have to go to the settings of device to grant (activity recognition, body sensor) I found not granted and switch it on manually.

The app in which you use HekaWidget does not need these permissions (activity recognition, body sensor) for Google Fit integration. Google Fit does the work of getting those permissions and tracking user data.

**Comment by Pulkit07** [comment]
Hey @BurierAbdalwahhabElia, I checked server logs and can see that data is being sent correctly. Following is a sample:

```
{
"data":
      {
            "steps": [
                {
                    "value": 36,
                    "source": "google_fit",
                    "end_time": 1679299375241.1433,
                    "start_time": 1679299303241.1394,
                    "source_device": null
                },
                {
                    "value": 2,
                    "source": "google_fit",
                    "end_time": 1679299856046.4578,
                    "start_time": 1679299796046.4578,
                    "source_device": null
                },
                {
                    "value": 21,
                    "source": "google_fit",
                    "end_time": 1679299993819.8513,
                    "start_time": 1679299933819.8513,
                    "source_device": null
                },
            ]
        },
        "uuid": "yam****@***9.com"
}
```

If I am correct, your webhook is `http://165.***.***.123/api/send` right?

**Comment by BurierAbdalwahhabElia** [comment]
Yes, this is my webhook url.
Thank you , I am very grateful to you.
Is this data from my device? It's real?
If am right, there is no any problem now in my project? Why I am not see any data in my response?

**Comment by BurierAbdalwahhabElia** [comment]
I have another question, why this data not sent live and real time? I mean while I am walking, this should send my steps to server. What mechanicism of this data sending work?

**Comment by Pulkit07** [comment]
> Yes, this is my webhook url. Thank you , I am very grateful to you. Is this data from my device? It's real? If am right, there is no any problem now in my project? Why I am not see any data in my response?

Yes, this was a sample of real data from a device with `uuid: y*m*hdi@1**9.com` and connected to google fit using email `a**a**limoh*****@gmail.com`.

I see that we are sending data correctly, can you debug/log the request you are getting on the webhook and see what you are getting?

If you want more help in debugging, I can jump over a call to help you out.

**Comment by Pulkit07** [comment]
> I have another question, why this data not sent live and real time? I mean while I am walking, this should send my steps to server. What mechanicism of this data sending work?

We rely on Google Fit APIs to get the data. There is delay because of how Google process the data and the options it provide to sync. Are you interested in live step data?

**Comment by BurierAbdalwahhabElia** [comment]
> > I have another question, why this data not sent live and real time? I mean while I am walking, this should send my steps to server. What mechanicism of this data sending work?
> 
> We rely on Google Fit APIs to get the data. There is delay because of how Google process the data and the options it provide to sync. Are you interested in live step data?

Yes, my app depend on this features. I am very grateful to you if you can doing this. Thanks

**Comment by BurierAbdalwahhabElia** [comment]
> > Yes, this is my webhook url. Thank you , I am very grateful to you. Is this data from my device? It's real? If am right, there is no any problem now in my project? Why I am not see any data in my response?
> 
> Yes, this was a sample of real data from a device with `uuid: y*m*hdi@1**9.com` and connected to google fit using email `a**a**limoh*****@gmail.com`.
> 
> I see that we are sending data correctly, can you debug/log the request you are getting on the webhook and see what you are getting?
> 
> If you want more help in debugging, I can jump over a call to help you out.

I will check my server as soon as possible. And tell you what's new in this matter.

**Comment by Pulkit07** [comment]
> > > I have another question, why this data not sent live and real time? I mean while I am walking, this should send my steps to server. What mechanicism of this data sending work?
> > 
> > 
> > We rely on Google Fit APIs to get the data. There is delay because of how Google process the data and the options it provide to sync. Are you interested in live step data?
> 
> Yes, my app depend on this features. I am very grateful to you if you can doing this. Thanks

We can try to achieve this; however, there are various limitations around the Google Fit ecosystem. We will need to understand your use cases first before we can promise anything on this front. Can you share what are your use cases?

In case you can't share here on a public Github issue, feel free to share details on pulkit (at) hekahealth (dot) co.

**Comment by BurierAbdalwahhabElia** [comment]
> > > > I have another question, why this data not sent live and real time? I mean while I am walking, this should send my steps to server. What mechanicism of this data sending work?
> > > 
> > > 
> > > We rely on Google Fit APIs to get the data. There is delay because of how Google process the data and the options it provide to sync. Are you interested in live step data?
> > 
> > Yes, my app depend on this features. I am very grateful to you if you can doing this. Thanks
> 
> We can try to achieve this; however, there are various limitations around the Google Fit ecosystem. We will need to understand your use cases first before we can promise anything on this front. Can you share what are your use cases?
> 
> In case you can't share here on a public Github issue, feel free to share details on pulkit (at) hekahealth (dot) co.

My cases of use in app that show to users their steps and convert it to points for buying our products as a prize and motivate sports of walking to Reducing pollution from car smoke.

**Comment by Pulkit07** [comment]
> > > > > I have another question, why this data not sent live and real time? I mean while I am walking, this should send my steps to server. What mechanicism of this data sending work?
> > > > 
> > > > 
> > > > We rely on Google Fit APIs to get the data. There is delay because of how Google process the data and the options it provide to sync. Are you interested in live step data?
> > > 
> > > 
> > > Yes, my app depend on this features. I am very grateful to you if you can doing this. Thanks
> > 
> > 
> > We can try to achieve this; however, there are various limitations around the Google Fit ecosystem. We will need to understand your use cases first before we can promise anything on this front. Can you share what are your use cases?
> > In case you can't share here on a public Github issue, feel free to share details on pulkit (at) hekahealth (dot) co.
> 
> My cases of use in app that show to users their steps and convert it to points for buying our products as a prize and motivate sports of walking to Reducing pollution from car smoke.

In that case, I don't think you need live data. A sync every 10 minutes should be sufficient. What do you think?

**Comment by BurierAbdalwahhabElia** [comment]
Hi,
No, I need to live steps counter because I will show this steps value on notification as service.
Can you doing this please? Because if i don't find this features in this plugin, I have to search about another one or another approach to achieve this.
Help me please.

**Comment by BurierAbdalwahhabElia** [comment]
> > Yes, this is my webhook url. Thank you , I am very grateful to you. Is this data from my device? It's real? If am right, there is no any problem now in my project? Why I am not see any data in my response?
> 
> Yes, this was a sample of real data from a device with `uuid: y*m*hdi@1**9.com` and connected to google fit using email `a**a**limoh*****@gmail.com`.
> 
> I see that we are sending data correctly, can you debug/log the request you are getting on the webhook and see what you are getting?
> 
> If you want more help in debugging, I can jump over a call to help you out.

hi,
this is my response format
this still getting null:

`"uuid": "y****di@1**9.com",
  "data": {
    "steps": [
      {
        "value": null,
        "source": null,
        "end_time": null,
        "start_time": null
      }
    ],
    "calories": [
      {
        "value": null,
        "source": null,
        "end_time": null,
        "start_time": null
      }
    ],
    "move_minutes": [
      {
        "value": null,
        "source": null,
        "end_time": null,
        "start_time": null
      }
    ]
  }
}`

and That is kind of you if you called at this phone number to understand what i suppose doing?
+964 783 124 8192 on whatsup.

**Comment by BurierAbdalwahhabElia** [comment]
Hi,
I use a new UUID (ya*li@**23)
And no data getting.
Our structure code in my server side is:

`"data"=>[
                 "steps"=> [
                               ["value"=> $request->value,
                                "source"=> $request->source,
                                "end_time"=> $request->end_time,
                                "start_time"=> $request->start_time]
                  ],
                  "calories"=>[
                   [ "value"=> $request->value,
                    "source"=> $request->source,
                    "end_time"=> $request->end_time,
                    "start_time"=> $request->start_time] ],
            "move_minutes"=> [
               [ "value"=> $request->value,
                "source"=> $request->source,
                "end_time"=> $request->end_time,
                "start_time"=> $request->start_time]]
        ]]`

Is this structure right?
Can you provide some code to server side if you can? I am in trouble with this issue.
Thanks.

**Comment by Pulkit07** [comment]
> > > Yes, this is my webhook url. Thank you , I am very grateful to you. Is this data from my device? It's real? If am right, there is no any problem now in my project? Why I am not see any data in my response?
> > 
> > 
> > Yes, this was a sample of real data from a device with `uuid: y*m*hdi@1**9.com` and connected to google fit using email `a**a**limoh*****@gmail.com`.
> > I see that we are sending data correctly, can you debug/log the request you are getting on the webhook and see what you are getting?
> > If you want more help in debugging, I can jump over a call to help you out.
> 
> hi, this is my response format this still getting null:
> 
> `"uuid": "y****di@1**9.com", "data": { "steps": [ { "value": null, "source": null, "end_time": null, "start_time": null } ], "calories": [ { "value": null, "source": null, "end_time": null, "start_time": null } ], "move_minutes": [ { "value": null, "source": null, "end_time": null, "start_time": null } ] } }`
> 
> and That is kind of you if you called at this phone number to understand what i suppose doing? +964 783 124 8192 on whatsup.

Sure, I have dropped a message on WhatsApp.

**Comment by Pulkit07** [comment]
> Hi, I use a new UUID (ya*li@**23) And no data getting.

Does the google fit connected with that have any data? It looks like there is no data to be synced.

**Comment by Pulkit07** [comment]
Hi @BurierAbdalwahhabElia, were you able to fix the issue based on our discussion over a google meet call?

**Comment by BurierAbdalwahhabElia** [comment]
> Hi @BurierAbdalwahhabElia, were you able to fix the issue based on our discussion over a google meet call?

Hi, I am very grateful to your help, but when I know this is not free plugin, I find another plugin. Thanks for your help.

**Comment by Pulkit07** [comment]
Hey, it's a free plugin until 100 users. If you plan to use just Google
Fit, we can increase the user quota under free plan for you.

The paid plan involves Fitbit, Strava, Apple Healthkit and other platforms.
